###Scripts version 2012###

diff --git a/data_from_portwine/scripts/functions_helper b/data_from_portwine/scripts/functions_helper
--- a/data_from_portwine/scripts/functions_helper
+++ b/data_from_portwine/scripts/functions_helper
@@ -78,14 +78,14 @@ try_force_link_dir () {
 
 try_download () {
     set -o pipefail
-    wget -c -t 5 -T 2 "$1" --output-document="$2" 2>&1 | \
+    wget -c -t 5 -T 20 "$1" --output-document="$2" 2>&1 | \
     sed -u 's/.* \([0-9]\+%\)\ \+\([0-9,.]\+.\) \(.*\)/\1\n#Downloading at \1\/, \2\/s, ETA \3/; s/^20[0-9][0-9].*/#Done./' | \
     zenity --progress --percentage=0 --title="Download $(basename $1)" --text=Starting... --auto-close --auto-kill --width=500 --height=90
     [ "${PIPESTATUS[0]}" != 0 ] && print_error "failed to download $1. Scipping." && return 1 || return 0
 }
 
 try_download_silent () {
-    wget -c -t 5 -T 2 "$1" --output-document="$2"
+    wget -c -t 5 -T 20 "$1" --output-document="$2"
     [ "$?" != 0 ] && print_error "failed to download $1. Scipping." && return 1 || return 0
 }
 
@@ -122,6 +122,12 @@ unpack_tar_xz () {
 unpack_tar_gz () {
     set -o pipefail
     tar -xzvf "$1" -C "$2" | sszen
+    [ "${PIPESTATUS[0]}" != 0 ] && print_error "File unpacking error." && return 1 || return 0
+}
+
+unpack_tar () {
+    set -o pipefail
+    tar -xvf "$1" -C "$2" | sszen
     [ "${PIPESTATUS[0]}" != 0 ] && print_error "File unpacking error." && return 1 || return 0
 }
 
@@ -205,11 +211,8 @@ check_user_conf () {
 }
 
 init_wine_ver () {
-    if [ ! -z "${PW_WINE_VER}" ] && [ `echo "${PW_WINE_VER}" | grep "PROTON_GE"` ] 
-    then export PW_WINE_USE=proton_ge
-    elif [ ! -z "${PW_WINE_VER}" ] && [ `echo "${PW_WINE_VER}" | grep "PROTON_STEAM"` ] 
-    then export PW_WINE_USE=proton_steam
-    fi
+    [ ! -z "${PW_WINE_VER}" ] && export PW_WINE_USE=`echo "${PW_WINE_VER}" | tr [[:lower:]] [[:upper:]]`
+    [ ! -z "${PW_WINE_USE}" ] && export PW_WINE_USE=`echo "${PW_WINE_USE}" | tr [[:lower:]] [[:upper:]]`
     unset PW_WINE_VER
     export WINEDIR="${PORT_WINE_PATH}/data/dist/${PW_WINE_USE}"
     export GST_PLUGIN_SYSTEM_PATH_1_0="${WINEDIR}/lib64/gstreamer-1.0:${WINEDIR}/lib/gstreamer-1.0"
@@ -234,6 +237,27 @@ init_wine_ver () {
     then export PATH="${WINEDIR}/bin:${PATH}"
     else export PATH="${WINEDIR}/bin"
     fi
+
+    if [ -d "${WINEDIR}/files" ] ; then
+        chmod -R 755 "${WINEDIR}"
+        for clear_dist_files in `ls "${WINEDIR}" | sed -e "s/^files$//g" | sed -e "s/^version$//g"` ; do 
+            rm -fr "${WINEDIR}/$clear_dist_files"
+        done
+        mv -f "${WINEDIR}/files"/* "${WINEDIR}/"
+        rm -fr "${WINEDIR}/files"
+    elif [ -f "${WINEDIR}/proton_dist.tar" ] ; then
+        unpack_tar "${WINEDIR}/proton_dist.tar" "${WINEDIR}/"
+        for clear_dist_files in `ls "${WINEDIR}" | sed -e "s/^bin$//g" | sed -e "s/^lib$//g" | sed -e "s/^lib64$//g" | sed -e "s/^share$//g" | sed -e "s/^version$//g"` ; do 
+            rm -fr "${WINEDIR}/$clear_dist_files"
+        done
+    fi
+
+    for copy_proton_dll in "dxvk" "vkd3d-proton" ; do
+        if [ ! -d "${WINEDIR}/lib/wine/${copy_proton_dll}/" ] ; then
+            try_copy_dir "${PORT_WINE_PATH}/data/dist/PROTON_STEAM/lib/wine/${copy_proton_dll}" "${WINEDIR}/lib/wine/"
+            try_copy_dir "${PORT_WINE_PATH}/data/dist/PROTON_STEAM/lib64/wine/${copy_proton_dll}" "${WINEDIR}/lib64/wine/"
+        fi
+    done
 }
 
 cabextract_fix () {
@@ -445,35 +469,33 @@ pw_tray_icon () {
 pw_init_db () {
     if [ ! -z "${portwine_exe}" ]; then
         export PORTWINE_DB=`echo "${portwine_exe}" | awk -F '/' 'NF>1{print $NF}' | sed s/".exe"/""/gi`
-#        export PATH_TO_GAME="$( cd "$( dirname "${portwine_exe}" )" >/dev/null 2>&1 && pwd )"
-#        export WIN_PATH_TO_GAME=`echo "C:${PATH_TO_GAME}" | sed "s%$WINEPREFIX%%g" | sed "s/drive_c//g" | sed 's#/#\\\#g'`
-    fi
-    if [ ! -z "${PORTWINE_DB}" ]; then
         PORTWINE_DB_FILE=`grep -ilw "#${PORTWINE_DB}" "${PORT_SCRIPTS_PATH}/portwine_db"/* | sed s/".exe"/""/gi`
         if [ ! -z "${PORTWINE_DB_FILE}" ]; then
             . "${PORTWINE_DB_FILE}"
             echo "Use ${PORTWINE_DB_FILE} db file."
-        else
-            . "${PORT_SCRIPTS_PATH}/portwine_db/default"
-            echo "Use default db file."
-        fi
+            init_wine_ver
+        fi       
     fi
-    init_wine_ver
+#        export PATH_TO_GAME="$( cd "$( dirname "${portwine_exe}" )" >/dev/null 2>&1 && pwd )"
+#        export WIN_PATH_TO_GAME=`echo "C:${PATH_TO_GAME}" | sed "s%$WINEPREFIX%%g" | sed "s/drive_c//g" | sed 's#/#\\\#g'`
 }
 
-pw_update_notifier () {
-    if [ ! -f "${PORT_WINE_TMP_PATH}/${portname}_ver" ] ; then
-        echo "10" > "${PORT_WINE_TMP_PATH}/${portname}_ver"
-    fi
-    if [ ! -f "${PORT_WINE_TMP_PATH}/update_notifier" ] ; then
-        echo "1" > "${PORT_WINE_TMP_PATH}/update_notifier"
-    fi
-    read "update_not" < "${PORT_WINE_TMP_PATH}/update_notifier"
-    if [ "${update_not}" = "1" ] ; then
-        if try_download_silent "${PW_FTP_URL}/current_version/${portname}_ver" "${PORT_WINE_TMP_PATH}/${portname}_cur_ver" ; then
-            read current_ver < "${PORT_WINE_TMP_PATH}/${portname}_cur_ver"
-            try_remove_file "${PORT_WINE_TMP_PATH}/${portname}_cur_ver"
-            if  [ ! -z "${current_ver}" ] && [ "${current_ver}" -gt "${install_ver}" ] ; then
+pw_port_update () {
+    ###PORT UPDATE###
+    if try_download_silent "https://github.com/Castro-Fidel/PortWINE/raw/master/data_from_portwine/scripts/var" "${PORT_WINE_TMP_PATH}/curent_var_ver" ; then
+        if [ ! -f "${PORT_WINE_TMP_PATH}/${portname}_ver" ] ; then
+            echo "10" > "${PORT_WINE_TMP_PATH}/${portname}_ver"
+        fi
+        export port_install_ver=`cat "${PORT_WINE_TMP_PATH}/${portname}_ver" | head -n 1`
+        if [ ! -f "${PORT_WINE_TMP_PATH}/update_notifier" ] ; then
+            echo "1" > "${PORT_WINE_TMP_PATH}/update_notifier"
+        fi
+        read "update_not" < "${PORT_WINE_TMP_PATH}/update_notifier"
+        if [ "${update_not}" = "1" ] ; then
+            export port_current_ver=`cat "${PORT_WINE_TMP_PATH}/curent_var_ver" | grep PORT_NEXT_VERSION | awk -F "=" '{print $2}'`
+            echo "Port version in github = ${port_current_ver}"
+            echo "Port version local = ${port_install_ver}"
+            if  [ ! -z "${port_current_ver}" ] && [ "${port_current_ver}" -gt "${port_install_ver}" ] ; then
                 xsd=`zenity --title  "${port_upd1}" --text "${port_upd2}" --list --radiolist --height=240 --column="${inst_set}" --column "${port_upd3}" \
                 TRUE "${port_upd4}" \
                 FALSE "${port_upd5}" \
@@ -490,49 +512,44 @@ pw_update_notifier () {
                 esac
             fi
         fi
-    fi
-    if [ ! -f "${HOME}/.config/.PortTime" ] ; then
-        echo "10" > "${HOME}/.config/.PortTime"
-    fi
-    read "port_time" < "${HOME}/.config/.PortTime"
-    if [ "${port_time}" -gt "1" ] ; then
-        port_time=$((${port_time}-1))
-        echo "${port_time}" > "${HOME}/.config/.PortTime"
-    else
-        xsd2=`zenity --title  "${port_time1}" --text "${port_time2}" --list --radiolist --height=230 --column="${inst_set3}" --column "${port_time3}" \
-        TRUE "${port_time4}" \
-        FALSE "${port_time5}" \
-        FALSE "${port_time6}" `
-        if [ $? = 1 ] ; then
-            echo "1" > "${HOME}/.config/.PortTime"
-        else
-            case $xsd2 in
-                "${port_time4}")
-                    xdg-open "$urlg" &
-                    echo "300" > "${HOME}/.config/.PortTime"
-                    exit 0 ;;
-                "${port_time5}")
-                    echo "75" > "${HOME}/.config/.PortTime" ;;
-                "${port_time6}")
-                    echo "150" > "${HOME}/.config/.PortTime" ;;
-            esac
+        if [ ! -f "${HOME}/.config/.PortTime" ] ; then
+            echo "10" > "${HOME}/.config/.PortTime"
         fi
-    fi
-}
-
-pw_scripts_update () {
-    if [ ! -f "${PORT_WINE_TMP_PATH}/scripts_ver" ] ; then
-        echo "2000" > "${PORT_WINE_TMP_PATH}/scripts_ver"
-    fi
-    export scripts_install_ver=`cat "${PORT_WINE_TMP_PATH}/scripts_ver" | head -n 1`
-    if [ ! -f "${PORT_WINE_TMP_PATH}/scripts_update_notifier" ] ; then
-            echo "1" > "${PORT_WINE_TMP_PATH}/scripts_update_notifier"
-    fi
-    read "scripts_update_not" < "${PORT_WINE_TMP_PATH}/scripts_update_notifier"
-    if [ "${scripts_update_not}" = "1" ] ; then
-        if try_download_silent "https://github.com/Castro-Fidel/PortWINE/raw/master/data_from_portwine/scripts/var" "${PORT_WINE_TMP_PATH}/scripts_cur_ver" ; then
-            export scripts_current_ver=`cat "${PORT_WINE_TMP_PATH}/scripts_cur_ver" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}'`
-            try_remove_file "${PORT_WINE_TMP_PATH}/scripts_cur_ver"
+        read "port_time" < "${HOME}/.config/.PortTime"
+        if [ "${port_time}" -gt "1" ] ; then
+            port_time=$((${port_time}-1))
+            echo "${port_time}" > "${HOME}/.config/.PortTime"
+        else
+            xsd2=`zenity --title  "${port_time1}" --text "${port_time2}" --list --radiolist --height=230 --column="${inst_set3}" --column "${port_time3}" \
+            TRUE "${port_time4}" \
+            FALSE "${port_time5}" \
+            FALSE "${port_time6}" `
+            if [ $? = 1 ] ; then
+                echo "1" > "${HOME}/.config/.PortTime"
+            else
+                case $xsd2 in
+                    "${port_time4}")
+                        xdg-open "$urlg" &
+                        echo "300" > "${HOME}/.config/.PortTime"
+                        exit 0 ;;
+                    "${port_time5}")
+                        echo "75" > "${HOME}/.config/.PortTime" ;;
+                    "${port_time6}")
+                        echo "150" > "${HOME}/.config/.PortTime" ;;
+                esac
+            fi
+        fi
+        ###SCRIPTS UPDATE###
+        if [ ! -f "${PORT_WINE_TMP_PATH}/scripts_ver" ] ; then
+            echo "2000" > "${PORT_WINE_TMP_PATH}/scripts_ver"
+        fi
+        export scripts_install_ver=`cat "${PORT_WINE_TMP_PATH}/scripts_ver" | head -n 1`
+        if [ ! -f "${PORT_WINE_TMP_PATH}/scripts_update_notifier" ] ; then
+                echo "1" > "${PORT_WINE_TMP_PATH}/scripts_update_notifier"
+        fi
+        read "scripts_update_not" < "${PORT_WINE_TMP_PATH}/scripts_update_notifier"
+        if [ "${scripts_update_not}" = "1" ] ; then
+            export scripts_current_ver=`cat "${PORT_WINE_TMP_PATH}/curent_var_ver" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}'`
             echo "Scripts version in github = ${scripts_current_ver}"
             echo "Scripts version local = ${scripts_install_ver}"
             if [ ! -z "${scripts_current_ver}" ] && [ "${scripts_current_ver}" -gt "${scripts_install_ver}" ] ; then
@@ -552,10 +569,8 @@ pw_scripts_update () {
                                 try_remove_file "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
                                 try_remove_dir "${PORT_WINE_TMP_PATH}/PortWINE-master/"
                                 echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
-                                "${pw_yad}" --title="Changelog" --borders=10 \
-                                --text="Скрипты были успешно обновлены.\nДля продолжения запуска порта нажмите ОК." \
-                                --text-align=center --text-info --show-uri --wrap --center --width=1200 --height=550 \
-                                --filename="${PORT_WINE_PATH}/data/changelog" --uri-color=red
+                                zenity --title="Changelog" --text-info --width=1200 --height=550 \
+                                --filename="${PORT_WINE_PATH}/data/changelog"
                                 [ "$?" == 0 ] && /bin/bash -c ${pw_full_command_line[*]} &
                                 exit 0
                             fi
@@ -569,6 +584,7 @@ pw_scripts_update () {
                 esac
             fi
         fi
+        try_remove_file "${PORT_WINE_TMP_PATH}/curent_var_ver"
     fi
 }
 
@@ -649,33 +665,57 @@ pw_gui_for_edit_db () {
 }
 
 pw_check_and_download_wine () {
-    if [ "${1}" == "proton_ge" ] ; then
-        if [ "`cat "${PORT_WINE_PATH}"/data/dist/proton_ge/version | head -n 1`" != "${PW_PROTON_GE_VER}" ]
-        then try_remove_dir "${PORT_WINE_PATH}/data/dist/proton_ge/"
+    [ ! -d "${PORT_WINE_PATH}/data/dist/" ] && create_new_dir "${PORT_WINE_PATH}/data/dist"
+    if [ "${1}" == "PROTON_GE" ] ; then
+        if [ "`cat "${PORT_WINE_PATH}"/data/dist/PROTON_GE/version | head -n 1`" != "${PW_PROTON_GE_VER}" ]
+        then try_remove_dir "${PORT_WINE_PATH}/data/dist/PROTON_GE/"
         fi
-        if [ ! -d "${PORT_WINE_PATH}/data/dist/proton_ge" ] ; then
-            print_info "Download and install proton_ge..."
-            if try_download "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/${PW_PROTON_GE_VER}/Proton-${PW_PROTON_GE_VER}.tar.gz" "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}.tar.gz" ; then
-                if unpack_tar_gz "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}.tar.gz" "${PORT_WINE_PATH}/data/tmp/" ; then
-                    mv -f "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}/files" "${PORT_WINE_PATH}/data/dist/proton_ge"
-                    echo "${PW_PROTON_GE_VER}" > "${PORT_WINE_PATH}/data/dist/proton_ge/version"
-                    try_remove_file "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}.tar.gz"
-                    try_remove_dir "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}"
-                    try_remove_dir "${PORT_WINE_PATH}/data/dist/proton_ge/share/default_pfx/"
+        if [ ! -d "${PORT_WINE_PATH}/data/dist/PROTON_GE" ] ; then
+            print_info "Download and install PROTON_GE..."
+            if try_download "https://github.com/Castro-Fidel/wine_builds/releases/download/${PW_PROTON_GE_VER}/${PW_PROTON_GE_VER}.tar.xz" "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}.tar.xz" ; then
+                if unpack_tar_xz "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}.tar.xz" "${PORT_WINE_PATH}/data/dist/" ; then
+                    echo "${PW_PROTON_GE_VER}" > "${PORT_WINE_PATH}/data/dist/PROTON_GE/version"
+                    try_remove_file "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}.tar.xz"
+                    try_remove_dir "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}"
                 else
-                    try_remove_file "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}.tar.gz"
-                    try_remove_dir "${PORT_WINE_PATH}/data/tmp/Proton-${PW_PROTON_GE_VER}"
-                    try_remove_dir "${PORT_WINE_PATH}/data/dist/proton_ge"
+                    try_remove_file "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}.tar.xz"
+                    try_remove_dir "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_GE_VER}"
+                    try_remove_dir "${PORT_WINE_PATH}/data/dist/PROTON_GE"
 
                     `zenity --error --title "Error..." \
-                    --text "Failed to download WINE: proton_ge.\nCheck internet connection and press OK" \
+                    --text "Failed to download WINE: PROTON_GE.\nCheck internet connection and press OK" \
                     --no-wrap ` > /dev/null 2>&1 && pw_check_and_download_wine
                 fi
             else
                 `zenity --error --title "Error..." \
-                --text "Failed to download WINE: proton_ge.\nCheck internet connection and press OK" \
+                --text "Failed to download WINE: PROTON_GE.\nCheck internet connection and press OK" \
                 --no-wrap ` > /dev/null 2>&1 && pw_check_and_download_wine
             fi
+        fi
+    fi
+    if [ "`cat "${PORT_WINE_PATH}"/data/dist/PROTON_STEAM/version | head -n 1`" != "${PW_PROTON_STEAM_VER}" ]
+    then try_remove_dir "${PORT_WINE_PATH}/data/dist/PROTON_STEAM/"
+    fi
+    if [ ! -d "${PORT_WINE_PATH}/data/dist/PROTON_STEAM" ] ; then
+        print_info "Download and install PROTON_STEAM..."
+        if try_download "https://github.com/Castro-Fidel/wine_builds/releases/download/${PW_PROTON_STEAM_VER}/${PW_PROTON_STEAM_VER}.tar.xz" "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}.tar.xz" ; then
+            if unpack_tar_xz "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}.tar.xz" "${PORT_WINE_PATH}/data/dist/" ; then
+                echo "${PW_PROTON_STEAM_VER}" > "${PORT_WINE_PATH}/data/dist/PROTON_STEAM/version"
+                try_remove_file "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}.tar.xz"
+                try_remove_dir "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}"
+            else
+                try_remove_file "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}.tar.xz"
+                try_remove_dir "${PORT_WINE_PATH}/data/tmp/${PW_PROTON_STEAM_VER}"
+                try_remove_dir "${PORT_WINE_PATH}/data/dist/PROTON_STEAM"
+
+                `zenity --error --title "Error..." \
+                --text "Failed to download WINE: PROTON_STEAM.\nCheck internet connection and press OK" \
+                --no-wrap ` > /dev/null 2>&1 && pw_check_and_download_wine
+            fi
+        else
+            `zenity --error --title "Error..." \
+            --text "Failed to download WINE: PROTON_STEAM.\nCheck internet connection and press OK" \
+            --no-wrap ` > /dev/null 2>&1 && pw_check_and_download_wine
         fi
     fi
 }
diff --git a/data_from_portwine/scripts/portwine_db/League of Legends b/data_from_portwine/scripts/portwine_db/League of Legends
--- a/data_from_portwine/scripts/portwine_db/League of Legends
+++ b/data_from_portwine/scripts/portwine_db/League of Legends
@@ -1,14 +1,15 @@
 #!/bin/bash
 #Author: xuser
 #LeagueClient.exe
+#RiotClientServices.exe
 #Rating=1-5
 #####################examples###########################
-##export PW_COMMENT_DB="blablabla"
+export PW_COMMENT_DB="Check openssl in your system!"
 ##export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
 ##export PW_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks)
 ##export WINEDLLOVERRIDES="blabla=n,b"
-export LAUNCH_PARAMETERS="('--launch-product=league_of_legends' '--launch-patchline=live')"                # Additional launch options
-export PW_WINE_USE=proton_ge
+export LAUNCH_PARAMETERS=("--launch-product=league_of_legends" "--launch-patchline=live")                # Additional launch options
+export PW_WINE_USE=PROTON_GE
 export PW_VULKAN_USE=dxvk
 ##export PW_DXR_ON=1
 ##export PW_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
@@ -21,17 +22,42 @@ export PW_VULKAN_USE=dxvk
 ##export ENABLE_VKBASALT=1
 ##export PW_VKBASALT_EFFECTS="FakeHDR:cas"        # Use Reshade in others games (dx9-12 to vulkan only)
 ##export PW_VKBASALT_FFX_CAS="0.75"               # FidelityFX Contrast Adaptive Sharpening (min 0 - max 1)
-##export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
-##export PW_NO_ESYNC=0                            # Do not use eventfd-based in-process synchronization primitives
+export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
+export PW_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
 ##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
 ##export PW_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
 ##export PW_HEAP_DELAY_FREE=1
 ##export PW_WINE_ALLOW_XIM=1                      # Disable XIM support until libx11 >= 1.7 is widespread
-export WINEARCH=win32                           # defaut = win64
-export WINEPREFIX="${PORT_WINE_PATH}/data/pfx_x86"
+export WINEARCH=win32                             # defaut = win64
+export WINEPREFIX="${PORT_WINE_PATH}/data/pfx_lol"
+export PW_MONO_VER="6.3.0"
+export PW_GECKO_VER="2.47.2"
 ##export PW_WINEDBG_DISABLE=1                     # Disabled WINEDBG
 ##export PW_USE_TERMINAL=1                        # Force run in terminal
 ##export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI
+
+check_port_for_lol () {
+    process=LeagueClientUx.exe
+    uxpid=$(timeout 2m sh -c "until pidof ${process}; do sleep 1; done")
+    if [[ ! -n $uxpid ]]; then
+        echo "Could not find process ${process}"
+        exit 1
+    fi
+    echo "LeagueClientUx pid: ${uxpid}"
+    port=$(xargs -0 < /proc/${uxpid}/cmdline | sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p')
+    if [[ ! -n $port ]]; then
+        echo "Could not find port"
+        exit 1
+    fi
+    echo "Waiting for port ${port}"
+    kill -STOP ${uxpid}
+    timeout 5m sh -c "
+    until openssl s_client -connect :${port} <<< Q > /dev/null 2>&1; do
+    sleep 1
+    done"
+    kill -CONT ${uxpid}
+}
+
 add_in_start_portwine () {
     if [ "$(cat /proc/sys/abi/vsyscall32)" -ne 0 ] ; then
         zenity --question --title="Fix for LoL anti-cheat" \
@@ -39,4 +65,5 @@ add_in_start_portwine () {
         [ "$?" = 1 ] && exit 0
         pkexec sh -c 'sysctl -w abi.vsyscall32=0 && sysctl -p'
     fi
+    check_port_for_lol &
 }
diff --git a/data_from_portwine/scripts/runlib b/data_from_portwine/scripts/runlib
--- a/data_from_portwine/scripts/runlib
+++ b/data_from_portwine/scripts/runlib
@@ -40,6 +40,8 @@ start_portwine () {
     export MEDIACONV_VIDEO_TRANSCODED_FILE="${PORT_WINE_TMP_PATH}"/transcoded_video.foz
     export STAGING_SHARED_MEMORY=1
     export PW_FORCE_LARGE_ADDRESS_AWARE=1
+    export WINEDLLPATH="${WINEDIR}/lib64/wine:${WINEDIR}/lib/wine"
+
     create_new_dir "${WINEDIR}/share/wine/"
     try_remove_dir "${WINEDIR}"/share/wine/gecko
     try_remove_dir "${WINEDIR}"/share/wine/mono
@@ -254,7 +256,7 @@ start_portwine () {
     if [ ! -d "${WINEPREFIX}/drive_c/users/steamuser/My Documents" ]
     then try_force_link_dir "${WINEPREFIX}/drive_c/users/steamuser/Documents" "${WINEPREFIX}/drive_c/users/steamuser/My Documents"
     fi
-    var_winedlloverride_update "steam_api,steam_api64,steamclient,steamclient64=n"
+    var_winedlloverride_update "steam_api,steam_api64,steamclient,steamclient64=n;lsteamclient,GameOverlayRenderer,GameOverlayRenderer64,winemenubuilder.exe="
 
     # export TOTAL_VRAM=`"${PW_WINELIB}/runtime/bin/glxinfo" -B | grep Total | awk -F: '{print $2}' | awk '{print $1}'`
     # echo "TOTAL_VRAM=${TOTAL_VRAM}"
@@ -373,7 +375,7 @@ start_portwine () {
                 cabextract_fix
             fi
             ${pw_runtime} xterm -e env LD_LIBRARY_PATH="${PW_AND_RUNTIME_LIBRARY_PATH}${LD_LIBRARY_PATH}" "${PORT_WINE_TMP_PATH}/winetricks" -q -f ${PW_DLL_NEED_INSTALL}
-            if [ "${PW_WINE_USE}" != "proton_steam" ] ; then
+            if [ "${PW_WINE_VER_FROM_DB}" != "PROTON_STEAM" ] ; then
                 /bin/bash -c ${pw_full_command_line[*]} &
                 exit 0
             fi
@@ -425,15 +427,28 @@ pw_run () {
 }
 
 ###MAIN###
+[ $(id -u) -eq 0 ] && echo "Do not run the script from the superuser!" && zenity --error --text "Do not run the script from the superuser!" 2> /dev/null  && exit 1
 unset MANGOHUD MANGOHUD_DLSYM PW_NO_ESYNC PW_NO_FSYNC PW_VULKAN_USE WINEDLLOVERRIDES PW_NO_WRITE_WATCH PW_GUI_DISABLED_CS
 unset PW_CHECK_AUTOINSTAL PW_VKBASALT_EFFECTS PW_VKBASALT_FFX_CAS PORTWINE_DB PORTWINE_DB_FILE PW_DISABLED_CREAT_DB PW_YAD_SET
+export portname=PortProton
 
 cd "$(dirname "`readlink -f "$0"`")" && export PORT_SCRIPTS_PATH="$(pwd)"
 cd "${PORT_SCRIPTS_PATH}/../../" && export PORT_WINE_PATH="$(pwd)"
 export PORT_WINE_TMP_PATH="${PORT_WINE_PATH}/data/tmp"
+if [ -d "${PORT_WINE_PATH}/data/dist" ] ; then
+    chmod -R 755 "${PORT_WINE_PATH}/data/dist"
+    orig_IFS="$IFS"
+    IFS=$'\n'
+    for dist_dir in $(ls -1 "${PORT_WINE_PATH}/data/dist/") ; do
+        dist_dir_new=`echo "${dist_dir}" | awk '$1=$1' | sed -e s/[[:blank:]]/_/g`
+        if [ ! -d "${PORT_WINE_PATH}/data/dist/${dist_dir_new^^}" ] ; then
+            mv -- "${PORT_WINE_PATH}/data/dist/$dist_dir" "${PORT_WINE_PATH}/data/dist/${dist_dir_new^^}"
+        fi
+    done
+    IFS="$orig_IFS"
+fi
 create_new_dir "${PORT_WINE_TMP_PATH}"
 create_new_dir "${HOME}/.PortWINE/tmp"
-read "portname" < "${PORT_WINE_TMP_PATH}/portname" && export portname
 cd "${PORT_SCRIPTS_PATH}"
 . "${PORT_SCRIPTS_PATH}/var"
 
@@ -446,7 +461,6 @@ if [ ! -f "${PORT_WINE_TMP_PATH}/${portname}_loc" ] ; then
 fi
 . "${PORT_SCRIPTS_PATH}"/lang
 
-var_winedlloverride_update "winemenubuilder.exe="
 export urlg="https://portwine-linux.ru/portwine-faq/"
 export PW_FTP_URL="https://portwine-linux.ru/ftp"
 export PW_WINELIB="${HOME}/.PortWINE/libs${PW_LIBS_VER}"
@@ -458,11 +472,10 @@ check_user_conf
 
 if [ -z "${INSTALLING_PORT}" ] ; then
     . "${USER_CONF}"
+    pw_port_update
     pw_download_libs
     pw_download_mono
     pw_download_gecko
-    pw_update_notifier
-    pw_scripts_update
     pw_init_db
     . "${USER_CONF}"
 fi
