Scripts version 1061

diff --git a/data_from_portwine/scripts/runlib b/data_from_portwine/scripts/runlib
--- a/data_from_portwine/scripts/runlib
+++ b/data_from_portwine/scripts/runlib
@@ -81,10 +81,13 @@ try_force_link_dir () {
 }
 try_download () {
     set -o pipefail
-    wget -c -t 10 -T 1 "$1" --output-document="$2" 2>&1 | \
+    wget -c -t 5 -T 2 "$1" --output-document="$2" 2>&1 | \
     sed -u 's/^[a-zA-Z\-].*//; s/.* \{1,2\}\([0-9]\{1,3\}\)%.*/\1\n#Downloading... \1%/; s/^20[0-9][0-9].*/#Done./' | \
     zenity --progress --percentage=0 --title="Download $(basename $1)" --text=Starting... --auto-close --auto-kill --width=500 --height=90
     [ "${PIPESTATUS[0]}" != 0 ] && print_error "failed to download $1. Scipping." && return 1 || return 0 
+}
+zenity_error_download () {
+    `zenity --error --title "Error..." --text "You will need to check internet connettion,\nand press OK for repeet download" --no-wrap ` > /dev/null 2>&1
 }
 create_new_dir () {
     if [ ! -d "$1" ] ; then
@@ -146,6 +149,92 @@ PW_STOP_PROGRESS_BAR () {
     do kill -n 9 `pgrep -a yad | grep "\-\-progress" | awk '{print $1}' | head -n 1`
     done
 }
+PW_LOAD_LIBS () {
+    if [ ! -e "${WINELIB}/run.sh" ] || [ ! -e "${WINELIB}/usr/bin/yad" ] || [ ! -e "${WINELIB}/usr/lib/p7zip/7zr" ] \
+    || [ ! -e "${WINELIB}/amd64/usr/bin/vkcube" ] || [ ! -e "${WINELIB}/amd64/usr/bin/xterm" ] || \
+    [ -e "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" ] ; then 
+        print_info "Download and install libraries..."
+        if try_download "https://github.com/Castro-Fidel/PortWINE/releases/download/libs${pw_libs_ver}/libs${pw_libs_ver}.tar.xz" "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" ; then
+            if unpack_tar_xz "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" "${HOME}/.PortWINE/" ; then 
+                try_remove_file "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz"
+            else   
+                try_remove_dir "${HOME}/.PortWINE/libs${pw_libs_ver}"
+                try_remove_file "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz"
+                `zenity --error --title "Error..." \
+                --text "Failed to download runtime libraries.\nCheck internet connection and press OK" \
+                --no-wrap ` > /dev/null 2>&1 && PW_LOAD_LIBS
+            fi
+        else
+            `zenity --error --title "Error..." \
+            --text "Failed to download runtime libraries.\nCheck internet connection and press OK" \
+            --no-wrap ` > /dev/null 2>&1 && PW_LOAD_LIBS
+        fi
+    fi
+    try_remove_dir "${WINELIB}/pinned_libs_32"
+    try_remove_dir "${WINELIB}/pinned_libs_64"
+    export pw_yad="${WINELIB}/usr/bin/yad"
+    export pw_zstd="${WINELIB}/usr/bin/zstd"
+    export pw_7z="${WINELIB}/usr/lib/p7zip/7zr"
+    if [ -x "`which xterm 2>/dev/null`" ]; then
+        export SYS_XTERM=`which xterm`
+        export PW_XTERM="${SYS_XTERM} -geometry 159x37 -e" 
+    else
+        export PW_XTERM="${WINELIB}/amd64/usr/bin/xterm -geometry 159x37 -e"        
+    fi
+}
+
+PW_DOWNLOAD_MONO () { 
+    if [ ! -d "${HOME}/.PortWINE/mono/wine-mono-${mono_ver}" ] ; then 
+        echo "######################################################"
+        print_info "Download and install wine mono..."
+        if try_download "${url_mono}" "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz" ; then
+            create_new_dir "${HOME}/.PortWINE/mono"
+            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz" "${HOME}/.PortWINE/mono/"
+            then 
+                try_remove_dir "${HOME}/.PortWINE/mono/wine-mono-${mono_ver}-x86"
+                zenity_error_download && PW_DOWNLOAD_MONO
+            fi
+            try_remove_file "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz"
+        else 
+            zenity_error_download && PW_DOWNLOAD_MONO  
+        fi
+    fi
+}
+PW_DOWNLOAD_GECKO () {
+    if [ ! -d "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86" ] ; then 
+        echo "######################################################"
+        echo "Download and install wine gecko x86..."
+        if try_download "${url_gecko_x86}" "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz" ; then
+            create_new_dir "${HOME}/.PortWINE/gecko"
+            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz" "${HOME}/.PortWINE/gecko/"
+            then 
+                try_remove_dir "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86"
+                zenity_error_download && PW_DOWNLOAD_GECKO
+            fi
+            try_remove_file "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz"
+        else 
+            zenity_error_download && PW_DOWNLOAD_GECKO
+        fi
+    fi
+        if [ ! -d "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86_64" ] ; then 
+        echo "######################################################"
+        echo "Download and install wine gecko x86_64..."
+        if try_download "${url_gecko_x86_64}" "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz" ; then
+            create_new_dir "${HOME}/.PortWINE/gecko"
+            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz" "${HOME}/.PortWINE/gecko/"
+            then 
+                try_remove_dir "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86_64"
+                zenity_error_download && PW_DOWNLOAD_GECKO
+            fi
+            try_remove_file "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz"
+        else 
+            zenity_error_download && PW_DOWNLOAD_GECKO            
+        fi
+    fi
+    create_new_dir "${WINEDIR}/share/wine/"
+    try_force_link_dir "${HOME}/.PortWINE/gecko" "${WINEDIR}"/share/wine/      
+    try_force_link_dir "${HOME}/.PortWINE/mono" "${WINEDIR}"/share/wine/ 
+}  
 START_PORTWINE ()
     {
     if [ -x "`which konsole 2>/dev/null`" ]; then export PW_TERM="konsole --nofork -e"
@@ -166,7 +255,7 @@ START_PORTWINE ()
                 try_remove_file "${PW_VULKAN_DLL}/dxvk-${PW_DXVK_VER}.tar.gz"
             else
                 try_remove_file "${PW_VULKAN_DLL}/dxvk-${PW_DXVK_VER}.tar.gz"                
-                `zenity --error --title "Error..." --text "You will need to change DXVK version in db file!" --no-wrap ` > /dev/null 2>&1
+                `zenity --error --title "Error..." --text "You will need check internet connettion,\nor change DXVK version in db file!" --no-wrap ` > /dev/null 2>&1
                 PW_EDIT_DB & exit 1
             fi
         else 
@@ -372,18 +461,13 @@ UPDATE_WINETRICKS () {
     W_TRX_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
     W_TRX_EXT_VER="$(curl -s --list-only ${W_TRX_URL} | grep -i 'WINETRICKS_VERSION=' | sed 's/WINETRICKS_VERSION=//')"
     print_info "Version winetricks on server: ${W_TRX_EXT_VER}"
-    if  [ ! -f "${PORT_WINE_TMP_PATH}/winetricks" ] ; then
-        try_download "${W_TRX_URL}" "${PORT_WINE_TMP_PATH}/winetricks" 
-        chmod u+x "${PORT_WINE_TMP_PATH}/winetricks"
-    else
-        W_TRX_INT_VER="$(cat "${PORT_WINE_TMP_PATH}/winetricks" | grep -i 'WINETRICKS_VERSION=' | sed 's/WINETRICKS_VERSION=//')"
-        print_info "Version winetricks in port: ${W_TRX_INT_VER}"
-        if [ "$W_TRX_INT_VER" != "$W_TRX_EXT_VER" ] ; then
-            if try_download "${W_TRX_URL}" "${PORT_WINE_TMP_PATH}/winetricks_new" ; then
-                mv -f "${PORT_WINE_TMP_PATH}/winetricks_new" "${PORT_WINE_TMP_PATH}/winetricks"
-                W_TRX_INT_VER="$(cat "${PORT_WINE_TMP_PATH}/winetricks" | grep -i 'WINETRICKS_VERSION=' | sed 's/WINETRICKS_VERSION=//')" && print_info "Winetricks version in port has been updated (${W_TRX_INT_VER})" 
-                chmod u+x "${PORT_WINE_TMP_PATH}/winetricks"
-            fi
+    W_TRX_INT_VER="$(cat "${PORT_WINE_TMP_PATH}/winetricks" | grep -i 'WINETRICKS_VERSION=' | sed 's/WINETRICKS_VERSION=//')"
+    print_info "Version winetricks in port: ${W_TRX_INT_VER}"
+    if [ ! -f "${PORT_WINE_TMP_PATH}/winetricks" ] || [ "$W_TRX_INT_VER" != "$W_TRX_EXT_VER" ] ; then
+        if try_download "${W_TRX_URL}" "${PORT_WINE_TMP_PATH}/winetricks_new" ; then
+            mv -f "${PORT_WINE_TMP_PATH}/winetricks_new" "${PORT_WINE_TMP_PATH}/winetricks"
+            W_TRX_INT_VER="$(cat "${PORT_WINE_TMP_PATH}/winetricks" | grep -i 'WINETRICKS_VERSION=' | sed 's/WINETRICKS_VERSION=//')" && print_info "Winetricks version in port has been updated (${W_TRX_INT_VER})" 
+            chmod u+x "${PORT_WINE_TMP_PATH}/winetricks"
         fi
     fi
     if  [ -f "${PORT_WINE_TMP_PATH}/winetricks" ] ; then
@@ -437,7 +521,23 @@ RUN_WINETRICKS_FROM_DB () {
         echo "Set to win${PW_WINDOWS_VER}"
     fi
 }
-
+PW_INIT_DB () {
+    if [ ! -z "${portwine_exe}" ]; then
+        export PORTWINE_DB=`echo "${portwine_exe}" | awk -F '/' 'NF>1{print $NF}' | sed s/".exe"/""/gi`
+        export PATH_TO_GAME="$( cd "$( dirname "${portwine_exe}" )" >/dev/null 2>&1 && pwd )"
+        export WIN_PATH_TO_GAME=`echo "C:${PATH_TO_GAME}" | sed "s%$WINEPREFIX%%g" | sed "s/drive_c//g" | sed 's#/#\\\#g'`           
+    fi
+    if [ ! -z "${PORTWINE_DB}" ]; then
+        PORTWINE_DB_FILE=`grep -ilw "#${PORTWINE_DB}" "${PORT_SCRIPTS_PATH}/portwine_db"/* | sed s/".exe"/""/gi`
+        if [ ! -z "${PORTWINE_DB_FILE}" ]; then
+            . "${PORTWINE_DB_FILE}"
+            echo "Use ${PORTWINE_DB_FILE} db file."
+        else
+            . "${PORT_SCRIPTS_PATH}/portwine_db/default"
+            echo "Use default db file."
+        fi
+    fi
+}
 PW_UPDATE () {
     if [ ! -f "${PORT_WINE_TMP_PATH}/${portname}_ver" ] ; then
         echo "10" > "${PORT_WINE_TMP_PATH}/${portname}_ver"
@@ -612,17 +712,20 @@ PW_SCRIPTS_UPDATE () {
             echo "######################################################"
             echo "Update scripts..."
             try_remove_file "${PORT_WINE_TMP_PATH}/scripts.tar.xz"
-            try_download "${PW_FTP_URL}/dist/scripts.tar.xz" "${PORT_WINE_TMP_PATH}/scripts.tar.xz"
-            tar -Jxvf "${PORT_WINE_TMP_PATH}/scripts.tar.xz" -C "${PORT_WINE_PATH}/data/"
-            if [ "$?" == "0" ] ; then
-                try_remove_file "${PORT_WINE_TMP_PATH}/scripts.tar.xz"
-                echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
-                "${pw_yad}" --title="Changelog" --borders=10 \
-                --text="Скрипты были успешно обновлены.\nДля продолжения запуска порта нажмите ОК." \
-                --text-align=center --text-info --show-uri --wrap --center --width=1200 --height=550 \
-                --filename="${PORT_WINE_PATH}/data/changelog"
-                [ "$?" == 0 ] && /bin/bash -c ${pw_full_command_line[*]} & 
-                exit 0
+            if try_download "${PW_FTP_URL}/dist/scripts.tar.xz" "${PORT_WINE_TMP_PATH}/scripts.tar.xz" ; then
+                tar -Jxvf "${PORT_WINE_TMP_PATH}/scripts.tar.xz" -C "${PORT_WINE_PATH}/data/"
+                if [ "$?" == "0" ] ; then
+                    try_remove_file "${PORT_WINE_TMP_PATH}/scripts.tar.xz"
+                    echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
+                    "${pw_yad}" --title="Changelog" --borders=10 \
+                    --text="Скрипты были успешно обновлены.\nДля продолжения запуска порта нажмите ОК." \
+                    --text-align=center --text-info --show-uri --wrap --center --width=1200 --height=550 \
+                    --filename="${PORT_WINE_PATH}/data/changelog" --uri-color=red 
+                    [ "$?" == 0 ] && /bin/bash -c ${pw_full_command_line[*]} & 
+                    exit 0
+                fi
+            else 
+                zenity_error_download && PW_SCRIPTS_UPDATE
             fi
         fi
     fi
@@ -658,30 +761,22 @@ PW_RUN () {
         fi
     fi
 }
-
+#####MAIN#####
 cd "$(dirname "`readlink -f "$0"`")" && export PORT_SCRIPTS_PATH="$(pwd)"
 cd "${PORT_SCRIPTS_PATH}/../../" && export PORT_WINE_PATH="$(pwd)"
-export PORT_WINE_TMP_PATH="${PORT_WINE_PATH}/data/tmp"
+export PORT_WINE_TMP_PATH="${PORT_WINE_PATH}/data/tmp" 
+create_new_dir "${PORT_WINE_TMP_PATH}"
+create_new_dir "${HOME}/.PortWINE/tmp"
 read "portname" < "${PORT_WINE_TMP_PATH}/portname" && export portname
 cd "${PORT_SCRIPTS_PATH}" 
 . "${PORT_SCRIPTS_PATH}/var"  
-create_new_dir "${PORT_WINE_TMP_PATH}"
-create_new_dir "${HOME}/.PortWINE/tmp"
-try_remove_dir "${PORT_SCRIPTS_PATH}/vars"
 
-if [ ! -e "${PORT_WINE_TMP_PATH}/${portname}_loc" ]; then
+if [ ! -f "${PORT_WINE_TMP_PATH}/${portname}_loc" ] ; then
 	SET_LANG=`zenity --title  "Install $portname" --text "Select the language" --list --radiolist \
-	--column="Set:" --column "Language:" \
-	TRUE "RUS" \
-	FALSE "ENG" `
+	--column="Set:" --column "Language:" TRUE "RUS" FALSE "ENG" `
 	echo "${SET_LANG}" > "${PORT_WINE_TMP_PATH}/${portname}_loc"
 fi
-
 . "${PORT_SCRIPTS_PATH}"/lang
-
-if [ ! -e "${PORT_WINE_TMP_PATH}/${portname}_ver" ]; then
-	echo "10" > "${PORT_WINE_TMP_PATH}/${portname}_ver"
-fi
 
 var_winedlloverride_update "winemenubuilder.exe="
 export url_mono="https://github.com/madewokherd/wine-mono/releases/download/wine-mono-${mono_ver}/wine-mono-${mono_ver}-x86.tar.xz"
@@ -702,95 +797,10 @@ export install_ver=`cat "${PORT_WINE_TMP_PATH}/${portname}_ver" | head -n 1`
 export scripts_install_ver=`cat "${PORT_WINE_TMP_PATH}/scripts_ver" | head -n 1`
 
 if [ -z "${INSTALLING_PORT}" ] ; then
-    if [ ! -e "${WINELIB}/run.sh" ] || [ ! -e "${WINELIB}/usr/bin/yad" ] || [ ! -e "${WINELIB}/usr/lib/p7zip/7zr" ] \
-    || [ ! -e "${WINELIB}/amd64/usr/bin/vkcube" ] || [ ! -e "${WINELIB}/amd64/usr/bin/xterm" ] || \
-    [ -e "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" ] ; then 
-        print_info "Download and install libraries..."
-        if try_download "https://github.com/Castro-Fidel/PortWINE/releases/download/libs${pw_libs_ver}/libs${pw_libs_ver}.tar.xz" "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" ; then
-            if unpack_tar_xz "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz" "${HOME}/.PortWINE/" ; then 
-                try_remove_file "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz"
-            else   
-                try_remove_dir "${HOME}/.PortWINE/libs${pw_libs_ver}"
-                try_remove_file "${HOME}/.PortWINE/tmp/libs${pw_libs_ver}.tar.xz"
-                `zenity --error --title "Error..." --text "Failed to download runtime libraries.\nCheck internet connection and restart PortProton" --no-wrap ` > /dev/null 2>&1
-                exit 0
-            fi
-        else
-            `zenity --error --title "Error..." --text "Failed to download runtime libraries.\nCheck internet connection and restart PortProton" --no-wrap ` > /dev/null 2>&1
-            exit 1
-        fi
-    fi
-    if [ -e "${WINELIB}/run.sh" ]; then 
-        echo "######################################################"
-        echo "Runtime libraries is enabled"
-        try_remove_dir "${WINELIB}/pinned_libs_32"
-        try_remove_dir "${WINELIB}/pinned_libs_64"
-        export pw_yad="${WINELIB}/usr/bin/yad"
-        export pw_zstd="${WINELIB}/usr/bin/zstd"
-        export pw_7z="${WINELIB}/usr/lib/p7zip/7zr"
-        if [ -x "`which xterm 2>/dev/null`" ]; then
-            export SYS_XTERM=`which xterm`
-            export PW_XTERM="${SYS_XTERM} -geometry 159x37 -e" 
-        else
-            export PW_XTERM="${WINELIB}/amd64/usr/bin/xterm -geometry 159x37 -e"        
-        fi
-    else
-        echo "######################################################"
-        echo "Runtime libraries is disabled"
-    fi
-    if [ ! -d "${HOME}/.PortWINE/mono/wine-mono-${mono_ver}" ] ; then 
-        echo "######################################################"
-        print_info "Download and install wine mono..."
-        if try_download "${url_mono}" "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz" ; then
-            create_new_dir "${HOME}/.PortWINE/mono"
-            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz" "${HOME}/.PortWINE/mono/"
-            then try_remove_dir "${HOME}/.PortWINE/mono/wine-mono-${mono_ver}-x86"
-            fi
-            try_remove_file "${HOME}/.PortWINE/tmp/wine-mono-${mono_ver}-x86.tar.xz" 
-        fi
-    fi
-    if [ ! -d "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86" ] ; then 
-        echo "######################################################"
-        echo "Download and install wine gecko x86..."
-        if try_download "${url_gecko_x86}" "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz" ; then
-            create_new_dir "${HOME}/.PortWINE/gecko"
-            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz" "${HOME}/.PortWINE/gecko/"
-            then try_remove_dir "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86"
-            fi
-            try_remove_file "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86.tar.xz"
-        fi
-    fi
-        if [ ! -d "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86_64" ] ; then 
-        echo "######################################################"
-        echo "Download and install wine gecko x86_64..."
-        if try_download "${url_gecko_x86_64}" "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz" ; then
-            create_new_dir "${HOME}/.PortWINE/gecko"
-            if ! unpack_tar_xz "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz" "${HOME}/.PortWINE/gecko/"
-            then try_remove_dir "${HOME}/.PortWINE/gecko/wine-gecko-${gecko_ver}-x86_64"
-            fi
-            try_remove_file "${HOME}/.PortWINE/tmp/wine-gecko-${gecko_ver}-x86_64.tar.xz"
-        fi
-    fi
-    create_new_dir "${WINEDIR}/share/wine/"
-    try_force_link_dir "${HOME}/.PortWINE/gecko" "${WINEDIR}"/share/wine/      
-    try_force_link_dir "${HOME}/.PortWINE/mono" "${WINEDIR}"/share/wine/ 
-
-    if [ ! -z "${portwine_exe}" ]; then
-        export PORTWINE_DB=`echo "${portwine_exe}" | awk -F '/' 'NF>1{print $NF}' | sed s/".exe"/""/gi`
-        export PATH_TO_GAME="$( cd "$( dirname "${portwine_exe}" )" >/dev/null 2>&1 && pwd )"
-        export WIN_PATH_TO_GAME=`echo "C:${PATH_TO_GAME}" | sed "s%$WINEPREFIX%%g" | sed "s/drive_c//g" | sed 's#/#\\\#g'`           
-    fi
-    if [ ! -z "${PORTWINE_DB}" ]; then
-        PORTWINE_DB_FILE=`grep -ilw "#${PORTWINE_DB}" "${PORT_SCRIPTS_PATH}/portwine_db"/* | sed s/".exe"/""/gi`
-        if [ ! -z "${PORTWINE_DB_FILE}" ]; then
-            . "${PORTWINE_DB_FILE}"
-            echo "Use ${PORTWINE_DB_FILE} db file."
-        else
-            . "${PORT_SCRIPTS_PATH}/portwine_db/default"
-            echo "Use default db file."
-        fi
-    fi
+    PW_LOAD_LIBS
+    PW_DOWNLOAD_MONO
+    PW_DOWNLOAD_GECKO
+    PW_INIT_DB
+    PW_UPDATE
+    PW_SCRIPTS_UPDATE
 fi
-
-[ -z "${INSTALLING_PORT}" ] && PW_UPDATE
-[ -z "${INSTALLING_PORT}" ] && PW_SCRIPTS_UPDATE
