Scripts version 2252

diff --git a/data_from_portwine/scripts/yad_gui b/data_from_portwine/scripts/yad_gui
--- a/data_from_portwine/scripts/yad_gui
+++ b/data_from_portwine/scripts/yad_gui
@@ -1,30 +1,50 @@
 #!/usr/bin/env bash
 # Author: Castro-Fidel (linux-gaming.ru)
 ########################################################################
-zenity_info () {
+yad_info () {
     print_info "$@"
-    zenity --info --no-wrap --text "$@" 2> /dev/null
-}
-export -f zenity_info
-
-zenity_error () {
-    print_error "$@"
-    zenity --error --no-wrap --text "$@" 2> /dev/null
-}
-export -f zenity_error
-
-zenity_error_download () {
-    zenity --question --title "$loc_gui_error" --text "$loc_gui_error_download\n" --no-wrap --ok-label="Repeat" --cancel-label="Skip"
-    if [[ "$?" != 0 ]] ; then
-        return 1
-    else
-        return 0
+    if [[ ! -f "${pw_yad_v12_3}" ]] ; then
+        local pw_yad_v12_3="yad" 
+        command -v "${pw_yad_v12_3}" &>/dev/null || fatal "yad not found"
     fi
+    "${pw_yad_v12_3}" --no-wrap --text "$@" --width=400 --height=50 --borders=15 --title "INFO" \
+    --window-icon="$PW_GUI_ICON_PATH/portproton.svg" --image="$PW_GUI_ICON_PATH/info.png" \
+    --center --text-align=center --button=OK 2>/dev/null
+}
+export -f yad_info
+
+yad_error () {
+    print_error "$@"
+    if [[ ! -f "${pw_yad_v12_3}" ]] ; then
+        local pw_yad_v12_3="yad" 
+        command -v "${pw_yad_v12_3}" &>/dev/null || fatal "yad not found"
+    fi
+    "${pw_yad_v12_3}" --no-wrap --text "$@" --width=400 --borders=15 --title "ERROR" \
+    --window-icon="$PW_GUI_ICON_PATH/portproton.svg" --image="$PW_GUI_ICON_PATH/error.png" \
+    --center --text-align=center --button=EXIT 2>/dev/null
+}
+export -f yad_error
+
+yad_error_download () {
+    if [[ ! -f "${pw_yad_v12_3}" ]] ; then
+        local pw_yad_v12_3="yad" 
+        command -v "${pw_yad_v12_3}" &>/dev/null || fatal "yad not found"
+    fi
+    "${pw_yad_v12_3}" --text "$loc_gui_error_download" --width=400 --borders=15 --title "$loc_gui_error" \
+    --window-icon="$PW_GUI_ICON_PATH/portproton.svg" --image="$PW_GUI_ICON_PATH/download.png" \
+    --no-wrap --center --text-align=center --button=SKIP:1 --button=REPEAT:0 2>/dev/null
+    [[ "$?" != 0 ]] && return 1 || return 0
 }
 
 gui_question () {
-    zenity --question --title "${inst_set}." --text "$1" --no-wrap &>/dev/null
-    [ $? -eq "0" ] && return 0 || return 1
+    if [[ ! -f "${pw_yad_v12_3}" ]] ; then
+        local pw_yad_v12_3="yad" 
+        command -v "${pw_yad_v12_3}" &>/dev/null || fatal "yad not found"
+    fi
+    "${pw_yad_v12_3}" --text "${1}" --width=400 --borders=15 --title "${inst_set}." \
+    --window-icon="$PW_GUI_ICON_PATH/portproton.svg" --image="$PW_GUI_ICON_PATH/question.png" \
+    --no-wrap --center --text-align=center --button=NO:1 --button=YES:0 2>/dev/null
+    [[ "$?" != 0 ]] && return 1 || return 0
 }
 
 pw_start_progress_bar_cover () {
@@ -32,7 +52,7 @@ pw_start_progress_bar_cover () {
     PW_GIF_SIZE_X=`file "${PW_GIF_FILE}" | awk '{print $7 + 20}'`
     PW_GIF_SIZE_Y=`file "${PW_GIF_FILE}" | awk '{print $9 + 20}'`
     "${pw_yad}" --picture --filename="${PW_GIF_FILE}" --close-on-unfocus --no-buttons --undecorated --center \
-    --skip-taskbar --width=$PW_GIF_SIZE_X --height=$PW_GIF_SIZE_Y --window-icon="$PW_GUI_ICON_PATH/port_proton.png" > /dev/null 2>&1 &
+    --skip-taskbar --width=$PW_GIF_SIZE_X --height=$PW_GIF_SIZE_Y --window-icon="$PW_GUI_ICON_PATH/portproton.svg" > /dev/null 2>&1 &
     export PW_YAD_PID_PROGRESS_BAR_COVER="$!"
     return 0
 }
@@ -43,7 +63,7 @@ pw_start_progress_bar_cover_block () {
     PW_GIF_SIZE_X=`file "${PW_GIF_FILE}" | awk '{print $7 + 20}'`
     PW_GIF_SIZE_Y=`file "${PW_GIF_FILE}" | awk '{print $9 + 20}'`
     "${pw_yad}" --picture --filename="${PW_GIF_FILE}" --close-on-unfocus --no-buttons --undecorated --center \
-    --skip-taskbar --width=$PW_GIF_SIZE_X --height=$PW_GIF_SIZE_Y --window-icon="$PW_GUI_ICON_PATH/port_proton.png" > /dev/null 2>&1 &
+    --skip-taskbar --width=$PW_GIF_SIZE_X --height=$PW_GIF_SIZE_Y --window-icon="$PW_GUI_ICON_PATH/portproton.svg" > /dev/null 2>&1 &
     export PW_YAD_PID_PROGRESS_BAR_COVER_BLOCK="$!"
     return 0 
 }
@@ -113,7 +133,7 @@ pw_stop_progress_bar_cover_block () {
 export -f pw_stop_progress_bar_cover_block
 
 open_changelog () {
-    "${pw_yad}" --title="$loc_gui_changelog" --borders=3 --no-buttons --text-align=center \
+    "${pw_yad}" --title="$loc_gui_changelog" --borders=${YAD_BORDERS} --no-buttons --text-align=center \
     --text-info --show-uri --wrap --width=1200 --height=700 --uri-color=red \
     --filename="${PORT_WINE_PATH}/data/${PW_CHANGELOG_FILE}"
 }
@@ -145,9 +165,9 @@ pw_tray_icon () {
     }
     export -f tray_icon_click_exit
 
+    # --window-icon="$PW_GUI_ICON_PATH/portproton_tray.png" \
     "${pw_yad_v12_3}" --notification --no-middle \
-    --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
-    --image="$PW_GUI_ICON_PATH/port_proton.png" \
+    --image="$PW_GUI_ICON_PATH/portproton_tray.png" \
     --command="bash -c tray_icon_click" \
     --tooltip="PortProton" \
     --menu="| \
@@ -227,8 +247,8 @@ pw_gui_for_edit_db () {
     --field="${loc_gui_arg_gamescope}!${loc_gui_arg_gamescope_help} :CBE" "\\${GAMESCOPE_ARGS}!-r 60 -F fsr!" 2>/dev/null 1> "${PORT_WINE_TMP_PATH}/tmp_output_yad_fps_limit" 2>/dev/null &
     
     "${pw_yad_v12_3}" --paned --key="$KEY_EDIT_DB_GUI" --title "EDIT_DB" --text-align=center --height="800" \
-    --text "${loc_gui_edit_db} <b>${PORTWINE_DB}</b>\n ${loc_gui_edit_db_help}" --separator=" " --borders=3 \
-    --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
+    --text "${loc_gui_edit_db} <b>${PORTWINE_DB}</b>\n ${loc_gui_edit_db_help}" --separator=" " --borders=${YAD_BORDERS} \
+    --window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
     --button="${loc_gui_cancel}"!!"${loc_gui_cancel_help}":1 \
     --button="${loc_gui_reset_db}"!!"${loc_gui_reset_db_help}":2 \
     --button="${loc_gui_open_db}"!!"${loc_gui_open_db_help}":150 \
@@ -325,7 +345,7 @@ gui_proton_downloader () {
     fi
     pw_stop_progress_bar
     if [[ -z "${PROTON_GE_GIT}" ]] || [[ -z "${PROTON_PW_GIT}" ]] ; then
-        zenity_error "$loc_gui_check_new_wine_error"
+        yad_error "$loc_gui_check_new_wine_error"
         /usr/bin/env bash -c ${pw_full_command_line[*]} &
         exit 0
     fi
@@ -357,7 +377,7 @@ gui_proton_downloader () {
         `"${pw_yad}" --plug=$KEY_WINE --tabnum=5 --list --separator="" --listen \
         --column "$loc_gui_del_wine" < "${PORT_WINE_TMP_PATH}/tmp_installed_wine" 1> "${PORT_WINE_TMP_PATH}/tmp_installed_wine_set" 2>/dev/null` &
         `"${pw_yad}" --key=$KEY_WINE --notebook --width=500 --height=600 --text-align=center \
-        --window-icon="$PW_GUI_ICON_PATH/port_proton.png" --title "WINE MANAGER" --separator="" \
+        --window-icon="$PW_GUI_ICON_PATH/portproton.svg" --title "WINE MANAGER" --separator="" \
         --tab-pos=top --tab="PROTON-LG" --tab="WINE-KRON4EK"  --tab="PROTON-GE" --tab="WINE-GE-CUSTOM" --tab="$loc_gui_installed_wine" 2>/dev/null`
         YAD_WINE_STATUS="$?"
         if [[ "$YAD_WINE_STATUS" == "1" || "$YAD_WINE_STATUS" == "252" ]] ; then
@@ -419,12 +439,12 @@ gui_proton_downloader () {
                 else
                     try_remove_file "${PORT_WINE_PATH}/data/tmp/${PW_WINE_ARCHIVE}.tar.${archive_type}"
                     try_remove_dir "${PORT_WINE_PATH}/data/dist/${PW_WINE_ARCHIVE}"
-                    zenity_error_download && gui_proton_downloader || exit 1
+                    yad_error_download && gui_proton_downloader || exit 1
                 fi
             fi
         done
     else
-        zenity_error_download && gui_proton_downloader || exit 1
+        yad_error_download && gui_proton_downloader || exit 1
     fi
 
     if [[ "$1" != "silent" ]] ; then
@@ -451,9 +471,16 @@ gui_vkBasalt () {
         fi
     done
     if [[ ! -z "${PW_VKBASALT_FFX_CAS}" ]] ; then
-        VKBASALT_FFX_CAS_GUI=`bc -s <<< "${PW_VKBASALT_FFX_CAS}*100" | sed 's/\..*//'`
+        if [[ "$PW_VKBASALT_FFX_CAS" == "0" ]]
+        then export VKBASALT_FFX_CAS_GUI="0"
+        elif [[ "$PW_VKBASALT_FFX_CAS" == "1" ]]
+        then export VKBASALT_FFX_CAS_GUI="100"
+        elif [[ "$PW_VKBASALT_FFX_CAS" == 0.0* ]]
+        then export VKBASALT_FFX_CAS_GUI="$(echo "$PW_VKBASALT_FFX_CAS" | awk -F'0.0' '{print $2}')"
+        else export VKBASALT_FFX_CAS_GUI="$(echo "$PW_VKBASALT_FFX_CAS" | awk -F'0.' '{print $2}')"
+        fi
     else
-        VKBASALT_FFX_CAS_GUI=75
+        VKBASALT_FFX_CAS_GUI=66
     fi
     export old_IFS=$IFS
     export IFS="%"
@@ -466,8 +493,8 @@ gui_vkBasalt () {
     --field="AMD FidelityFX - Contrast Adaptive Sharpening"!"$loc_gui_ffx_cas":SCL "${VKBASALT_FFX_CAS_GUI}" \
     1> "${PORT_WINE_TMP_PATH}/tmp_yad_cas_set" 2>/dev/null &
 
-    "${pw_yad_v12_3}" --paned --key="$KEY_FX_GUI" --height="650" --title="vkBasalt" --center --borders=3 \
-    --separator=" " --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
+    "${pw_yad_v12_3}" --paned --key="$KEY_FX_GUI" --height="650" --title="vkBasalt" --center --borders=${YAD_BORDERS} \
+    --separator=" " --window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
     --button="$loc_gui_cancel"!!"$loc_gui_cancel_help":1 \
     --button="$loc_gui_disabled_vkbas"!!"$loc_gui_disabled_vkbas_help":180 \
     --button="$loc_gui_save_changes"!!"$loc_gui_save_changes_help":182 2>/dev/null
@@ -494,12 +521,13 @@ gui_vkBasalt () {
     GUI_FX_RESULT="${GUI_FX_RESULT}cas"
     export PW_VKBASALT_EFFECTS="${GUI_FX_RESULT}"
 
-    if [[ "$YAD_CAS_SET" == "0" ]] ; then
-        export PW_VKBASALT_FFX_CAS="0"
-    elif [[ "$YAD_CAS_SET" == "100" ]] ; then
-        export PW_VKBASALT_FFX_CAS="1"
-    else
-        export PW_VKBASALT_FFX_CAS="0`bc -s <<< "scale=2; $YAD_CAS_SET/100"`"
+    if [[ "$YAD_CAS_SET" == "0" ]]
+    then export PW_VKBASALT_FFX_CAS="0"
+    elif [[ "$YAD_CAS_SET" == "100" ]]
+    then export PW_VKBASALT_FFX_CAS="1"
+    elif [[ "$YAD_CAS_SET" -lt 10 ]]
+    then export PW_VKBASALT_FFX_CAS="0.0$YAD_CAS_SET"
+    else export PW_VKBASALT_FFX_CAS="0.$YAD_CAS_SET"
     fi
     edit_db_from_gui PW_VKBASALT_EFFECTS PW_VKBASALT_FFX_CAS ENABLE_VKBASALT
     /usr/bin/env bash -c ${pw_full_command_line[*]} &
@@ -557,8 +585,8 @@ gui_MangoHud () {
         --field="${loc_gui_mango_fps}!${loc_gui_mango_fps_help} :CB" "${FPS_LIMIT_VAR}!disabled!${GET_REFRESH_RATE}" \
         1> "${PORT_WINE_TMP_PATH}/tmp_yad_mh_fps_limit" 2>/dev/null &
 
-    "${pw_yad_v12_3}" --paned --key="$KEY_MH_GUI" --height="650" --title="MangoHud" --center --borders=3 \
-        --separator=" " --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
+    "${pw_yad_v12_3}" --paned --key="$KEY_MH_GUI" --height="650" --title="MangoHud" --center --borders=${YAD_BORDERS} \
+        --separator=" " --window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
         --button="$loc_gui_cancel"!!"$loc_gui_cancel_help":1 \
         --button="$loc_gui_disabled_mh"!!"$loc_gui_disabled_mh_help":182 \
         --button="$loc_gui_save_changes"!!"$loc_gui_save_changes_help":184 2>/dev/null
@@ -627,8 +655,8 @@ portwine_create_shortcut () {
 
     if [[ "$1" == "block_name" ]] ; then
         export name_desktop="${PORTPROTON_NAME}"
-        OUTPUT=$("${pw_yad}" --title="${inst_set}." --form --borders=3 \
-        --window-icon "$PW_GUI_ICON_PATH/port_proton.png" \
+        OUTPUT=$("${pw_yad}" --title="${inst_set}." --form --borders=${YAD_BORDERS} \
+        --window-icon "$PW_GUI_ICON_PATH/portproton.svg" \
         --image "${PORT_WINE_PATH}/data/img/${PORTPROTON_NAME}.png" \
         --field="${sc_info}":LBL "" \
         --field="  ${name_desktop}":LBL "" \
@@ -639,8 +667,8 @@ portwine_create_shortcut () {
         PW_YAD_OUT=$?
     else
         export name_desktop="${PORTPROTON_NAME}"
-        OUTPUT=$("${pw_yad}" --title="${inst_set}." --form --borders=3 \
-        --window-icon "$PW_GUI_ICON_PATH/port_proton.png" \
+        OUTPUT=$("${pw_yad}" --title="${inst_set}." --form --borders=${YAD_BORDERS} \
+        --window-icon "$PW_GUI_ICON_PATH/portproton.svg" \
         --image "${PORT_WINE_PATH}/data/img/${PORTPROTON_NAME}.png" \
         --field="${sc_info}":LBL "" \
         --field="${sc_name}:" "${name_desktop}" \
@@ -743,8 +771,8 @@ portwine_delete_shortcut () {
 }
 
 portwine_missing_shortcut () {
-    "${pw_yad}" --title="${loc_gui_error}." --form --borders=3 \
-    --window-icon "$PW_GUI_ICON_PATH/port_proton.png" \
+    "${pw_yad}" --title="${loc_gui_error}." --form --borders=${YAD_BORDERS} \
+    --window-icon "$PW_GUI_ICON_PATH/portproton.svg" \
     --image "$PW_GUI_ICON_PATH/error_file.png" \
     --text "$loc_gui_missing_shortcut" \
     --button="$loc_gui_delete_shortcut":0 \
